<a href="https://colab.research.google.com/github/Raghureddy720/python-practice/blob/main/Day12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

In [3]:
df=sns.load_dataset('taxis')
df

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,East Harlem North,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn

In [4]:
df.sample(10)

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
2852,2019-03-20 14:05:21,2019-03-20 14:39:22,2,11.20,35.5,0.00,0.0,36.30,yellow,credit card,Van Cortlandt Village,Lenox Hill East,Bronx,Manhattan
4895,2019-03-21 23:38:33,2019-03-21 23:51:01,1,2.25,10.0,2.76,0.0,16.56,yellow,credit card,Greenwich Village South,Stuy Town/Peter Cooper Village,Manhattan,Manhattan
2120,2019-03-13 17:20:03,2019-03-13 17:27:38,4,0.80,6.5,2.15,0.0,12.95,yellow,credit card,Times Sq/Theatre District,Midtown East,Manhattan,Manhattan
1077,2019-03-29 17:50:08,2019-03-29 18:10:22,1,1.54,12.5,0.00,0.0,16.80,yellow,cash,Kips Bay,Garment District,Manhattan,Manhattan
1587,2019-03-18 17:24:06,2019-03-18 17:27:34,1,0.45,4.0,0.00,0.0,8.30,yellow,cash,Clinton East,East Chelsea,Manhattan,Manhattan
5976,2019-03-10 13:32:29,2019-03-10 13:47:56,1,2.34,12.0,0.00,0.0,12.80,green,credit card,Bushwick South,Stuyvesant Heights,Brooklyn,Brooklyn
1740,2019-03-17 18:36:41,2019-03-17 19:22:27,1,12.50,41.0,8.35,0.0,50.15,yellow,credit card,JFK Airport,Bedford,Queens,Brooklyn
3032,2019-03-15 18:28:02,2019-03-15 18:42:45,1,2.60,12.0,3.25,0.0,19.55,yellow,credit card,Midtown East,Central Park,Manhattan,Manhattan
2059,2019-03-30 19:11:13,2019-03-30 19:23:45,1,1.80,10.0,2.65,0.0,15.95,yellow,credit card,Manhattan Valley,Yorkville West,Manhattan,Manhattan
6282,2019-03-12 23:54:38,2019-03-13 00:03:34,1,1.40,8.5,0.00,0.0,9.80,green,cash,East Harlem North,Central Harlem North,Manhattan,Manhattan

In [5]:
df.head(6)

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan
5,2019-03-11 10:37:23,2019-03-11 10:47:31,1,0.49,7.5,2.16,0.0,12.96,yellow,credit card,Times Sq/Theatre District,Midtown East,Manhattan,Manhattan

In [6]:
df.tail(6)

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
6427,2019-03-23 18:26:09,2019-03-23 18:49:12,1,7.07,20.0,0.00,0.0,20.00,green,cash,Parkchester,East Harlem South,Bronx,Manhattan
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,East Harlem North,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn

In [7]:
df['color'].isnull()

0       False
1       False
2       False
3       False
4       False
        ...
6428    False
6429    False
6430    False
6431    False
6432    False
Name: color, Length: 6433, dtype: bool

In [8]:
df['payment'].isnull().sum()

44

In [9]:
df.shape[0]

6433

In [11]:
(df.isnull().sum()/df.shape[0])*100

pickup             0.000000
dropoff            0.000000
passengers         0.000000
distance           0.000000
fare               0.000000
tip                0.000000
tolls              0.000000
total              0.000000
color              0.000000
payment            0.683973
pickup_zone        0.404166
dropoff_zone       0.699518
pickup_borough     0.404166
dropoff_borough    0.699518
dtype: float64

In [ ]:

#missing data handling
#1. imputation (fill in the blanks)
   #1.statistical measures
   #2.parameter domain:
#2. delete data
#rows
#columns

In [12]:
df

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,East Harlem North,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn

In [13]:
df.drop('pickup_zone',axis=1)
#permanently cant del

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Windsor Terrace,Brooklyn,Brooklyn

In [14]:
df

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,East Harlem North,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn

In [17]:
df.drop(['pickup_zone'],axis=1,inplace=True)

KeyError: "['pickup_zone'] not found in axis"

In [18]:
df

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Windsor Terrace,Brooklyn,Brooklyn

In [19]:
df.drop(['pickup','color'],axis=1,inplace=True)

In [20]:
df

,dropoff,passengers,distance,fare,tip,tolls,total,payment,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,credit card,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,cash,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,credit card,West Village,Manhattan,Manhattan
3,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,credit card,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,credit card,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,credit card,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,credit card,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,cash,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,credit card,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,credit card,Windsor Terrace,Brooklyn,Brooklyn

In [21]:
df.drop([2,3,6430,6432],axis=0,inplace=True)

In [22]:
df

,dropoff,passengers,distance,fare,tip,tolls,total,payment,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,credit card,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,cash,Upper West Side South,Manhattan,Manhattan
4,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,credit card,Yorkville West,Manhattan,Manhattan
5,2019-03-11 10:47:31,1,0.49,7.5,2.16,0.0,12.96,credit card,Midtown East,Manhattan,Manhattan
6,2019-03-26 21:17:29,1,3.65,13.0,2.00,0.0,18.80,credit card,Two Bridges/Seward Park,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...
6426,2019-03-28 08:07:46,1,0.71,4.5,0.50,0.0,5.80,credit card,Upper West Side North,Manhattan,Manhattan
6427,2019-03-23 18:49:12,1,7.07,20.0,0.00,0.0,20.00,cash,East Harlem South,Bronx,Manhattan
6428,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,credit card,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,credit card,East Concourse/Concourse Village,Queens,Bronx
6431,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,credit card,East Flatbush/Remsen Village,Brooklyn,Brooklyn

In [23]:
df.reset_index()

,index,dropoff,passengers,distance,fare,tip,tolls,total,payment,dropoff_zone,pickup_borough,dropoff_borough
0,0,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,credit card,UN/Turtle Bay South,Manhattan,Manhattan
1,1,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,cash,Upper West Side South,Manhattan,Manhattan
2,4,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,credit card,Yorkville West,Manhattan,Manhattan
3,5,2019-03-11 10:47:31,1,0.49,7.5,2.16,0.0,12.96,credit card,Midtown East,Manhattan,Manhattan
4,6,2019-03-26 21:17:29,1,3.65,13.0,2.00,0.0,18.80,credit card,Two Bridges/Seward Park,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...
6424,6426,2019-03-28 08:07:46,1,0.71,4.5,0.50,0.0,5.80,credit card,Upper West Side North,Manhattan,Manhattan
6425,6427,2019-03-23 18:49:12,1,7.07,20.0,0.00,0.0,20.00,cash,East Harlem South,Bronx,Manhattan
6426,6428,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,credit card,Central Harlem North,Manhattan,Manhattan
6427,6429,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,credit card,East Concourse/Concourse Village,Queens,Bronx
6428,6431,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,credit card,East Flatbush/Remsen Village,Brooklyn,Brooklyn

In [27]:
df.reset_index(drop=True)#its mandatory to apply reset index  after deleting rows from dataframe

,dropoff,passengers,distance,fare,tip,tolls,total,payment,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,credit card,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,cash,Upper West Side South,Manhattan,Manhattan
2,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,credit card,Yorkville West,Manhattan,Manhattan
3,2019-03-11 10:47:31,1,0.49,7.5,2.16,0.0,12.96,credit card,Midtown East,Manhattan,Manhattan
4,2019-03-26 21:17:29,1,3.65,13.0,2.00,0.0,18.80,credit card,Two Bridges/Seward Park,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...
6424,2019-03-28 08:07:46,1,0.71,4.5,0.50,0.0,5.80,credit card,Upper West Side North,Manhattan,Manhattan
6425,2019-03-23 18:49:12,1,7.07,20.0,0.00,0.0,20.00,cash,East Harlem South,Bronx,Manhattan
6426,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,credit card,Central Harlem North,Manhattan,Manhattan
6427,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,credit card,East Concourse/Concourse Village,Queens,Bronx
6428,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,credit card,East Flatbush/Remsen Village,Brooklyn,Brooklyn

In [28]:
df.shape[1]

11

In [29]:
df['payment']==1

0       False
1       False
4       False
5       False
6       False
        ...
6426    False
6427    False
6428    False
6429    False
6431    False
Name: payment, Length: 6429, dtype: bool

In [32]:
a=10
b=10
c=a+b
c

20

In [38]:
df['fare']>15

0       False
1       False
4       False
5       False
6       False
        ...
6426    False
6427     True
6428    False
6429     True
6431    False
Name: fare, Length: 6429, dtype: bool

In [39]:
df['payment']=='credit card'

0        True
1       False
4        True
5        True
6        True
        ...
6426     True
6427    False
6428     True
6429     True
6431     True
Name: payment, Length: 6429, dtype: bool

In [40]:
df[df['payment']=='credit card']

,dropoff,passengers,distance,fare,tip,tolls,total,payment,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:27:24,1,1.60,7.00,2.15,0.0,12.95,credit card,UN/Turtle Bay South,Manhattan,Manhattan
4,2019-03-30 13:37:14,3,2.16,9.00,1.10,0.0,13.40,credit card,Yorkville West,Manhattan,Manhattan
5,2019-03-11 10:47:31,1,0.49,7.50,2.16,0.0,12.96,credit card,Midtown East,Manhattan,Manhattan
6,2019-03-26 21:17:29,1,3.65,13.00,2.00,0.0,18.80,credit card,Two Bridges/Seward Park,Manhattan,Manhattan
8,2019-03-23 12:06:14,1,3.63,15.00,1.00,0.0,19.30,credit card,Midtown Center,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...
6425,2019-03-07 16:31:06,1,9.12,26.32,0.00,0.0,26.82,credit card,East New York,Brooklyn,Brooklyn
6426,2019-03-28 08:07:46,1,0.71,4.50,0.50,0.0,5.80,credit card,Upper West Side North,Manhattan,Manhattan
6428,2019-03-31 09:55:27,1,0.75,4.50,1.06,0.0,6.36,credit card,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 18:34:23,1,18.74,58.00,0.00,0.0,58.80,credit card,East Concourse/Concourse Village,Queens,Bronx
6431,2019-03-04 10:14:29,1,1.12,6.00,0.00,0.0,6.80,credit card,East Flatbush/Remsen Village,Brooklyn,Brooklyn